### ISSUE TITLE
Unable to login while in Firefox `Private Browsing` mode.

### ISSUE THREAD

**Issue by geeknik** [stumbleupon/stumblebar#3]
If you install this extension into Firefox and then immediately launch the Private Browsing mode (tracking protection disabled, stumbleupon.com and netdna-ssl.com whitelisted in ublock origin), the extension will not stay signed into your StumbleUpon account (a white on blue text overlay appears above the stumblebar saying `You got logged out`). A simple workaround is to sign-in to StumbleUpon before you enter Private Browsing mode and the extension should remember the state but that rather defeats the purpose of Private Browsing mode.

**Comment by anoakie** [comment]
#5  comments welcome.

**Comment by anoakie** [comment]
Pushed to the mozstore.  Should pass review in a few days.
