### ISSUE TITLE
Conversations aren't marked as read, Inbox counter never decreases

### ISSUE THREAD

**Issue by geeknik** [stumbleupon/stumblebar#4]
When I first launched the stumblebar and logged in, the Inbox icon was showing a 5. I went through and loaded all of the conversations that looked to be new, but they were never marked as read and the counter never decreased from 5. Browser console content in the attached screenshot: 
![untitled](https://cloud.githubusercontent.com/assets/466878/26650143/1a519f44-460e-11e7-804b-807d3301ff1c.png)

The message about the iframe which references a .jpg is where I clicked on a conversation to load the stumble. The MessageChannel.jsm is just noise from Firefox, I don't believe it is related to this issue.

**Comment by anoakie** [comment]
We have a server-side caching issue with the mark-as-read caches.  We've filed a ticket.  We'll update this issue when we've fixed it.

**Comment by geeknik** [comment]
Since the source code for the StumbleBar is open source, can I get the actual StumbleUpon server source code? :)
